### ISSUE TITLE
New repo structure

### ISSUE THREAD

**Issue by inyono** [serlo/infrastructure#106]

**Comment by kulla** [comment]
From the protocol:

* per project we want to have one repository (infrastructure uses them via refering to a commit, git tag, branch, ...)
* per environment we want to have one repository

**Comment by inyono** [comment]
Some ideas regarding naming (feel free to decide on something else @marinusma @kulla):
- Environments: `infrastructure-{production,staging,dev}`
- Projects: `infrastructure-{project}` or `{project}-infrastructure`. Maybe even `infrastructure-module-{project}`
- Something like `infrastructure-shared` or `infrastructure-module-shared` for global resources (e.g. db). Feel free to decide if we need/want to split that up further, e.g. `infrastructure-module-mysql`, probably depends on envs.

Furthermore:
- Would be nice if we can clean up the environments (i.e. live/{env}). E.g. they should all have the same order / naming of variables and modules to make diffs easy. Were possible, move stuff into modules so that the environment entries are super simple and only set stuff that differs (e.g. module versions, domain, available resources)

**Comment by marinusma** [comment]
Solved in the following repositories

Environment
https://github.com/serlo/infrastructure-env-dev
https://github.com/serlo/infrastructure-env-staging
https://github.com/serlo/infrastructure-env-production

Modules
https://github.com/serlo/infrastructure-modules-serlo.org
https://github.com/serlo/infrastructure-modules-shared
https://github.com/serlo/infrastructure-modules-kpi
https://github.com/serlo/infrastructure-modules-gcloud
https://github.com/serlo/infrastructure-modules-env-shared
https://github.com/serlo/infrastructure-env-dev

Fixes in KPI:
https://github.com/serlo/p_data-analysis-and-kpis/pull/98
