### ISSUE TITLE
Terraform Kubernetes Provider does not create a deployment with serviceaccount automount

### ISSUE THREAD

**Issue by rbock44** [serlo/infrastructure#15]
Looks like a bug in 1.70.
The deployment descriptor does not create automount of service account token.

**Comment by marinusma** [comment]
Can be fixed as described here: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/38#issuecomment-318581203

**Comment by gabzim** [comment]
Thanks for the workaround but there should be a way for this to work out of the box, I just wasted a couple of hours of my life tracking this down.
