### ISSUE TITLE
Optimize resource-limits and replicas for workloads/containers

### ISSUE THREAD

**Issue by marinusma** [serlo/infrastructure#4]
Please check the following workloads/containers and optimize the resource-limits and replicas:

- athene2
   - php
   - httpd
   - cloudSQLProxy
- editor-renderer
- editor-renderer-legacy
- comment-system
- ingress-nginx
- kpi
   - grafana
   - cloudSQLProxy

**Comment by rbock44** [comment]
Optimization der Resources hat nichts gebracht. Ich denke wir können das hier schließen.
