### ISSUE TITLE
Compare/Check all settings in Cloudflare

### ISSUE THREAD

**Issue by marinusma** [serlo/infrastructure#41]
Please compare all settings in Cloudflare of the current production environment with the new staging one. If there are any differences, please note them here and open new issues if necessary.

**Comment by marinusma** [comment]
There are a few PageRules for the current production env (serlo.org). Is it necessary to implement these also in staging? If yes, please describe how.

**Comment by inyono** [comment]
There are no page rules that are important for staging. Prod page rules are implemented in the cloudflare worker for the most part.
