### ISSUE TITLE
Implement Cronjobs for athene2

### ISSUE THREAD

**Issue by marinusma** [serlo/infrastructure#44]
TODOS:

- Describe the jobs
- Implement jobs (docker image) to easily run it via kubernetes
- Implement kubernetes cronjobs
- Test

**Comment by rbock44** [comment]
@marinusma  Which cron jobs are required? In principle we have a working solution in KPI. Which works with a pod running a script based on cron pattern.

**Comment by marinusma** [comment]
@inyono Do you know which cron jobs are required?

**Comment by marinusma** [comment]
Done #76
