### ISSUE TITLE
Warmup for athene2

### ISSUE THREAD

**Issue by marinusma** [serlo/infrastructure#46]
It's noticeably, that initial requests to the athene2 app after a fresh deployment take up to 10sec +. We have to optimize/fix this behaviour.

**Comment by marinusma** [comment]
Please test again in staging, if really necessary.

**Comment by rbock44** [comment]
From my experience a warm-up is not required. If database connection is working properly it takes max 10 seconds from what I observed. At least as long as we keep the liveness probe.
