### ISSUE TITLE
Refactor httpd.conf overwrite in module athene2

### ISSUE THREAD

**Issue by marinusma** [serlo/infrastructure#48]
There is already a httpd.conf file specified in the serlo.org project:
https://github.com/serlo/serlo.org/blob/master/packages/server/docker/httpd/httpd.conf

Currently with overwrite this httpd.conf in the infrastructure project (see module athene2).

Please change it as follows:
- httpd.conf in serlo.org project is the main config file and must not be overwritten
- httpd.conf loads a second config file named "XY"
- File XY can be "injected" in the infrastructure project

**Comment by inyono** [comment]
Implemented in `athene2-httpd@0.2.1`. Its config will include `/usr/local/apache2/conf/httpd-override.conf`
